version: "3"
services:
  cse251:
    image: cse251-project-2:latest
    container_name: cse251-project-2
    build: .
    platform: linux/x86_64
    volumes:
      - type: bind
        source: .
        target: /root/workspace
    environment:
      - DISPLAY=host.docker.internal:0
    entrypoint: $cmd
    tty: true
    stdin_open: true
